
project_id = "lczzaisvzahlqricnilo"

[functions.send-feedback-reminder]
verify_jwt = false

[functions.check-internship-status]
verify_jwt = false

[functions.scheduled-internship-check]
verify_jwt = false
